services:
  taskwise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # IMPORTANT FOR SELF-HOSTING: 
        # Replace this with your server's actual IP address or hostname
        # Example: http://192.168.1.10:3100 or http://taskwise.example.com/api
        - NEXT_PUBLIC_API_URL=http://YOUR_SERVER_IP:3100
    ports:
      - "3000:3000"  # Web UI
      - "3100:3100"  # Database API
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - taskwise-data:/app/data  # Persists your database using a named volume
      - taskwise-logs:/app/logs  # Stores logs in a named volume
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# Use named volumes for better portability across systems
volumes:
  taskwise-data:
    driver: local
  taskwise-logs:
    driver: local
