services:
  taskwise:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: /api
    ports:
      - "9002:9002"  # Web UI
      - "3100:3100"  # Database API
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: taskwise
    volumes:
      - taskwise-data:/app/data
      - taskwise-logs:/app/logs
      - /app/node_modules

volumes:
  taskwise-data:
    driver: local
  taskwise-logs:
    driver: local
